name: Compile CV for GitHub Pages (Cached - Find LuaLaTeX)

on:
  push:
    branches:
      - main # Trigger on push to your main branch

jobs:
  build_and_deploy_cv:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is crucial for pushing to the gh-pages branch!

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache TeX Live installation
        id: cache-texlive
        uses: actions/cache@v4
        with:
          path: /usr/share/texlive # Still cache this main directory
          key: ${{ runner.os }}-texlive-2025-v1
          restore-keys: |
            ${{ runner.os }}-texlive-2025-

      - name: Install TeX Live packages (FORCED INSTALL FOR TEST)
        # Keeping this forced for now until we confirm the path
        # You can re-add 'if: steps.cache-texlive.outputs.cache-hit != 'true'' later
        run: |
          echo "Forcing full TeX Live installation for diagnostic test..."
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-luatex texlive-extra-utils texlive-fonts-extra latexmk

      - name: Find LuaLaTeX executable path
        id: find-lualatex # Give this step an ID to store the path
        run: |
          # Use 'which' to find it if it's in PATH, or 'find' if it's not
          LUALATEX_PATH=$(which lualatex || find /usr -name lualatex -type f -executable 2>/dev/null | head -n 1)
          echo "Found lualatex at: $LUALATEX_PATH"
          echo "lualatex_path=$LUALATEX_PATH" >> $GITHUB_OUTPUT # Store path for later use

      - name: Add TeX Live binaries to PATH (Dynamic)
        # Only add to PATH if it's not already in /usr/bin or a standard location
        # This step is now more robust based on the actual found path
        run: |
          LUALATEX_DIR=$(dirname "${{ steps.find-lualatex.outputs.lualatex_path }}")
          if [[ "$LUALATEX_DIR" != "/usr/bin" && "$LUALATEX_DIR" != "/usr/local/bin" ]]; then
            echo "Adding $LUALATEX_DIR to PATH"
            echo "$LUALATEX_DIR" >> $GITHUB_PATH
          else
            echo "lualatex found in a standard PATH directory ($LUALATEX_DIR), no need to modify PATH."
          fi

      - name: Verify lualatex executable
        run: |
          echo "Checking PATH:"
          echo $PATH
          which lualatex # This should now find lualatex
          lualatex --version # This should now work!

      - name: Compile LaTeX document with latexmk
        run: |
          mkdir -p web
          cd web/
          latexmk -lualatex ../cv.tex

      - name: Prepare PDF for deployment
        run: |
          mkdir deploy_cv
          cp web/cv.pdf deploy_cv/cv.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_cv
          publish_branch: gh-pages
