name: Compile CV for GitHub Pages

on:
  push:
    branches:
      - main # Trigger on push to your main branch

jobs:
  build_and_deploy_cv:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is crucial for pushing to the gh-pages branch!

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache apt packages and lists
        id: cache-apt
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives # Cache downloaded .deb files
            /var/lib/apt/lists # Cache apt package lists
          key: ${{ runner.os }}-apt-${{ hashFiles('**/Dockerfile', '.github/workflows/*.yml') }}-v1 # Unique key based on OS, and any changes to workflow or Dockerfile
          restore-keys: |
            ${{ runner.os }}-apt- # Fallback for minor changes

      - name: Install TeX Live packages
        # This step will ALWAYS run to ensure proper system setup,
        # but apt will be fast if packages are already cached/installed.
        run: |
          echo "Installing/updating TeX Live packages..."
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-luatex texlive-extra-utils texlive-fonts-extra latexmk

      # Removed the 'Add TeX Live binaries to PATH' step as /usr/bin is already in PATH
      # Removed the 'Debug TeX Live installation and lualatex' step as it's no longer needed
      - name: Compile LaTeX document with latexmk
        run: |
          mkdir -p web # Ensure the web directory exists
          cd web/
          # Assuming cv.tex is in the root, go up one level to find it.
          # If cv.tex is also inside the 'web' folder (e.g., your-repo/web/cv.tex), just use 'latexmk -lualatex cv.tex'
          latexmk -lualatex ../cv.tex
        # The output cv.pdf will now be in the 'web/' directory

      - name: Prepare PDF for deployment
        run: |
          mkdir deploy_cv # Create a new temporary directory for deployment
          cp web/cv.pdf deploy_cv/cv.pdf # Copy the compiled PDF into the new directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_cv
          publish_branch: gh-pages
          # cname: yourdomain.com # Uncomment and set if you use a custom domain
