name: Compile CV for GitHub Pages (Cached - Test Bypass)

on:
  push:
    branches:
      - main # Trigger on push to your main branch

jobs:
  build_and_deploy_cv:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is crucial for pushing to the gh-pages branch!

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache TeX Live installation
        id: cache-texlive # Give this step an ID so we can reference its output
        uses: actions/cache@v4
        with:
          path: /usr/share/texlive # ONLY cache the main TeX Live installation directory
          key: ${{ runner.os }}-texlive-2025-v1 # IMPORTANT: Update this key (e.g., v2, v3) if you change the packages installed below!
          restore-keys: |
            ${{ runner.os }}-texlive-2025- # Fallback key for minor changes

      - name: Install TeX Live packages (FORCED INSTALL FOR TEST)
        # Removed: if: steps.cache-texlive.outputs.cache-hit != 'true'
        # This step will now always run, forcing a full apt install
        run: |
          echo "Forcing full TeX Live installation for diagnostic test..."
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-luatex texlive-extra-utils texlive-fonts-extra latexmk

      - name: Add TeX Live binaries to PATH
        run: |
          echo "/usr/share/texlive/texmf-dist/bin/x86_64-linux" >> $GITHUB_PATH

      - name: Debug TeX Live installation and lualatex
        run: |
          echo "--- Listing contents of /usr/share/texlive/texmf-dist/bin/x86_64-linux/ ---"
          ls -la /usr/share/texlive/texmf-dist/bin/x86_64-linux/ || echo "Directory not found or accessible."

          echo "--- Checking if lualatex exists and is executable ---"
          test -x /usr/share/texlive/texmf-dist/bin/x86_64-linux/lualatex && echo "lualatex is executable at expected path." || echo "lualatex is NOT executable or does not exist at expected path."

          echo "--- Attempting to run lualatex directly from its expected path ---"
          /usr/share/texlive/texmf-dist/bin/x86_64-linux/lualatex --version || echo "Direct lualatex execution failed. Check for missing dependencies."

      - name: Compile LaTeX document with latexmk
        run: |
          mkdir -p web # Ensure the web directory exists
          cd web/
          latexmk -lualatex ../cv.tex
        # The output cv.pdf will now be in the 'web/' directory

      - name: Prepare PDF for deployment
        run: |
          mkdir deploy_cv # Create a new temporary directory for deployment
          cp web/cv.pdf deploy_cv/cv.pdf # Copy the compiled PDF into the new directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy_cv
          publish_branch: gh-pages
          # cname: yourdomain.com # Uncomment and set if you use a custom domain
